# Sintaxis: usuario::contraseña
cas.authn.accept.enabled=false

# 1.  Configuramos el almacen de claves
server.ssl.key-store=file:/home/amh09h/cas7.3/cas-overlay-template/etc/cas/thekeystore
server.ssl.key-store-password=${key-store-password}
server.ssl.key-password=${key-password}
server.ssl.key-store-type=PKCS12

# 2. --- CONFIGURACIÓN LDAP ---

# Prioridad (LDAP será el método principal)
cas.authn.ldap[0].order=0
# Conexión al servidor (localhost puerto 389)
cas.authn.ldap[0].ldap-url=ldap://localhost:389
# Dónde buscar usuarios (La base que creamos)
cas.authn.ldap[0].base-dn=ou=usuarios,dc=sms,dc=carm,dc=es
# Filtro de búsqueda (Buscaremos por UID)
cas.authn.ldap[0].search-filter=uid={user}
cas.authn.ldap[0].principal-attribute-id=uid
# Cómo conectarse para buscar (Bind DN)
# Tipo: DIRECT (Intenta loguearse directamente con el usuario)
# Tipo: AUTHENTICATED (Usa el admin para buscar primero) -> Usaremos este por seguridad
cas.authn.ldap[0].type=AUTHENTICATED
cas.authn.ldap[0].bind-dn=cn=admin,dc=sms,dc=carm,dc=es
cas.authn.ldap[0].bind-credential=${bind-credential}

# Mapeo de atributos (Opcional por ahora, pero útil)
#cas.authn.ldap[0].principal-attribute-list=cn,mail,displayName
cas.authn.ldap[0].principal-attribute-list=uid:login,description:dni,givenName:nombre,sn:apellidos,mail:email,memberOf:ROLES

# 3. Carpeta donde CAS buscará los archivos JSON de servicios
cas.service-registry.json.location=file:/home/amh09h/cas7.3/cas-overlay-template/etc/cas/services/
# (Opcional) Indica a CAS que revise si hay cambios en los JSON cada 10 segundos
cas.service-registry.json.watcher-enabled=true
cas.service-registry.core.init-from-json=false

# 4. JDBC Contratos (después de LDAP auth)
cas.authn.attribute-repository.jdbc[0].order=0
cas.authn.attribute-repository.jdbc[0].url=jdbc:mariadb://localhost:3306/contratos?useSSL=false&serverTimezone=UTC
cas.authn.attribute-repository.jdbc[0].user=cas_user
cas.authn.attribute-repository.jdbc[0].password=${jdbc-password}
cas.authn.attribute-repository.jdbc[0].dialect=MARIADB
cas.authn.attribute-repository.jdbc[0].driver-class=org.mariadb.jdbc.Driver
cas.authn.attribute-repository.jdbc[0].sql=SELECT uid, nombre, activo as contrato_activo FROM contratos WHERE uid=?
cas.authn.attribute-repository.jdbc[0].username={user}
cas.authn.attribute-repository.jdbc[0].attributes.contrato_activo=contrato_activo

# 5. Implementación de autenticación delegada en GOOGLE
cas.authn.pac4j.google.enabled=true
cas.authn.pac4j.google.id=366269229562-43ebgo46r3vt0srchgvjtshtarbhkfrt.apps.googleusercontent.com
cas.authn.pac4j.google.secret=${google-secret}
cas.authn.pac4j.google.callback-url=https://localhost:8443/cas/login
cas.authn.pac4j.google.callback-url-type=QUERY_PARAMETER
cas.authn.pac4j.google.auto-redirect-type=NONE
#NONE / CLIENT / SERVER
# IMPORTANTE: Aumentar el tiempo de vida de los tickets de delegación
cas.ticket.tst.time-to-kill-in-seconds=300
# Scopes para atributos (email, nombre)
cas.authn.pac4j.google.scope=EMAIL_AND_PROFILE
#cas.authn.pac4j.google.scope=openid,email,profile
cas.authn.pac4j.google.display-name="Acceso a Portal del Paciente con Google"
cas.authn.pac4j.google.principal-id-attribute=email
# Importante: Esto activa la selección de proveedores en el login
cas.authn.pac4j.core.discovery-selection.selection-type=DYNAMIC
# Indicar a CAS que busque mensajes y estáticos en tu proyecto
cas.view.template-prefixes=classpath:/templates,file:/home/amh09h/cas7.3/cas-overlay-template/src/main/resources/templates
cas.message-bundle.base-names=file:/home/amh09h/cas7.3/cas-overlay-template/etc/cas/config/custom_messages,classpath:custom_messages,classpath:messages

# 6 --- CLAVES DE CIFRADO WEBFLOW ---
cas.webflow.crypto.signing.key=MyCidZ7aeLfbfVsuhVs7C64n9_nIt-m-pJQjFDdc9upNdSk6dvCV3Ey--YlW914dwOLgndIIpxTNZ-ur2wuGEA
cas.webflow.crypto.encryption.key=3qCwVixxVpi9UBP3nV6P6A

# Llaves criptográficas para Ticket Granting Cookie (TGC)
cas.tgc.crypto.encryption.key=eaGRAvtDo2tlz56Yh6BF8zBQCmpHN1JdZ9Z4fC7xv_-6AN-oh7CPFW7ivcJHIJREJgzN_5rD9_3ndxrb4M8Yag
cas.tgc.crypto.signing.key=RvXQcssoV35P-4-LITpYGikt_GHatwYD6a_9perXSaRfQXrGrCxSnVXMdeOEw_BfqH0NTCWycRDWlytLMNXsFg
#---------------------#
#--- LOGS & AUDITS ---#
#---------------------#


logging.config=file:/home/amh09h/cas7.3/cas-overlay-template/etc/cas/config/log4j2.xml
logging.level.org.apereo.cas=INFO

logging.level.org.pac4j.google=DEBUG
logging.level.org.apereo.cas.web.flow.actions.DelegatedClientAuthenticationAction=DEBUG
logging.level.org.apereo.cas.web.flow.DefaultDelegatedClientAuthenticationWebflowManager=DEBUG
logging.level.org.apereo.cas.authentication.principal.DefaultDelegatedAuthenticationCredentialExtractor=DEBUG
logging.level.org.apereo.cas.support.pac4j=DEBUG
logging.level.org.apereo.cas.ticket=DEBUG

logging.level.org.springframework.web=DEBUG
logging.level.org.apereo.cas.web.flow=DEBUG
logging.level.org.springframework.jdbc=DEBUG

# 1. Habilitar auditoría vía SLF4J
#Formato por defecto de la auditoría, en una sola línea separade por pipes
cas.audit.slf4j.enabled=true
cas.audit.slf4j.use-single-line=true
cas.audit.slf4j.singleline-separator=|

# 2. El formato ahora suele ser parte de la configuración general de auditoría
# En CAS 7.3, si no usas un formato personalizado, el DEFAULT es el predeterminado.
cas.audit.engine.enabled=true
cas.audit.engine.audit-format=DEFAULT

# 3. CABECERA DE IP (Importante para proxys/X-Forwarded-For)
cas.audit.engine.alternate-client-addr-header-name=X-Forwarded-For

# 4. APP CODE (El que te dio el error)
cas.audit.engine.alternate-server-addr-header-name=CAS
